/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable max-len */
const { v4: uuidv4 } = require('uuid');

export default {
  page400: {
    title: '400',
    message: 'Не туда попали',
    linkMessage: 'назад к страницам',
    link: '/',
  },
  page500: {
    title: '500',
    message: 'Мы уже фиксим',
    linkMessage: 'назад к страницам',
    link: '/',
  },
  loginPage: {
    formName: 'signin',
    formTitle: 'Вход',
    inputs: [
      {
        type: 'text',
        name: 'login',
        labelText: 'Логин',
        id: uuidv4(4),
        required: true,
        placeholder: 'Введите логин',
        ref: 'login_inputRef',
        errorRef: 'login_errorRef',
      },
      {
        type: 'password',
        labelText: 'Пароль',
        name: 'password',
        required: true,
        id: uuidv4(4),
        ref: 'password_inputRef',
        errorRef: 'password_errorRef',
      },
    ],
    formButton: {
      text: 'Войти',
    },
    addon: {
      text: null,
      link: '/register',
      linkText: 'Нет аккаунта?',
    },
  },
  registerPage: {
    formTitle: 'Регистрация',
    formName: 'signup',
    formButton: {
      text: 'Зарегистрироваться',
    },
    inputs: [
      {
        type: 'text',
        value: 'Иван',
        labelText: 'Имя',
        name: 'first_name',
        required: true,
        id: uuidv4(4),
        ref: 'first_name_inputRef',
        errorRef: 'first_name_errorRef',
      },
      {
        type: 'text',
        value: 'Иванов',
        labelText: 'Фамилия',
        name: 'second_name',
        required: true,
        id: uuidv4(4),
        ref: 'second_name_inputRef',
        errorRef: 'second_name_errorRef',
      },
      {
        type: 'text',
        value: null,
        labelText: 'Логин',
        name: 'login',
        required: true,
        id: uuidv4(4),
        ref: 'login_inputRef',
        errorRef: 'login_errorRef',
      },
      {
        type: 'text',
        value: null,
        labelText: 'Ник',
        name: 'display_name',
        required: true,
        id: uuidv4(4),
        ref: 'display_name_inputRef',
        errorRef: 'display_name_errorRef',
      },
      {
        type: 'email',
        value: null,
        labelText: 'E-mail',
        name: 'email',
        required: true,
        id: uuidv4(4),
        ref: 'email_inputRef',
        errorRef: 'email_errorRef',
      },
      {
        type: 'tel',
        labelText: 'Телефон',
        name: 'phone',
        required: true,
        autocomplete: 'on',
        id: uuidv4(4),
        ref: 'phone_inputRef',
        errorRef: 'phone_errorRef',
      },
      {
        type: 'password',
        labelText: 'Пароль',
        name: 'password',
        required: true,
        error: '',
        id: uuidv4(4),
        ref: 'password_inputRef',
        errorRef: 'password_errorRef',
      },
      {
        type: 'password',
        labelText: 'Пароль еще раз',
        name: 'repeat_password',
        required: true,
        id: uuidv4(4),
        ref: 'repeat_password_inputRef',
        errorRef: 'repeat_password_errorRef',
      },
    ],
    addon: {
      text: 'Уже зарегистрированы?',
      link: '/login',
      linkText: 'Войти',
    },
  },
  messenger: {
    addChatForm: {
      formName: 'addChat',
      formTitle: 'Создать чат',
      inputs: [
        {
          type: 'text',
          name: 'title',
          labelText: null,
          id: uuidv4(4),
          required: true,
          placeholder: 'Введите название чата',
          ref: 'title_inputRef',
          errorRef: 'title_errorRef',
        },
      ],
      formButton: {
        text: 'Добавить',
      },
    },
    messageInput: {
      name: 'message',
      placeholder: 'Введите сообщение',
      id: uuidv4(4),
    },
    searchForm: {
      formName: 'search',
      inputs: [
        {
          type: 'text',
          name: 'search',
          placeholder: 'найти чат',
          ref: 'search_inputRef',
          id: uuidv4(4),
        },
      ],
    },
  },
  profileDataPage: {
    avatarInput: {
      type: 'file',
      name: 'avatar',
      required: false,
      id: 'avatar-input',
      accept: 'image/*',
    },
    formTitle: null,
    formName: 'editPersonalData',
    formButton: {
      text: 'Сохранить',
    },
    inputs: [
      {
        type: 'text',
        value: '',
        labelText: 'Имя',
        id: uuidv4(4),
        name: 'first_name',
        required: false,
        ref: 'first_name_inputRef',
        errorRef: 'first_name_errorRef',
      },
      {
        type: 'text',
        value: '',
        labelText: 'Фамилия',
        id: uuidv4(4),
        name: 'second_name',
        required: false,
        ref: 'second_name_inputRef',
        errorRef: 'second_name_errorRef',
      },
      {
        type: 'text',
        value: null,
        labelText: 'Ник',
        id: uuidv4(4),
        name: 'display_name',
        required: false,
        ref: 'display_name_inputRef',
        errorRef: 'display_name_errorRef',
      },
      {
        type: 'text',
        value: null,
        labelText: 'Логин',
        id: uuidv4(4),
        name: 'login',
        required: false,
        ref: 'login_inputRef',
        errorRef: 'login_errorRef',
      },
      {
        type: 'email',
        value: null,
        labelText: 'E-mail',
        id: uuidv4(4),
        name: 'email',
        required: false,
        ref: 'email_inputRef',
        errorRef: 'email_errorRef',
      },
      {
        type: 'tel',
        labelText: 'Телефон',
        name: 'phone',
        id: uuidv4(4),
        required: false,
        ref: 'phone_inputRef',
        errorRef: 'phone_errorRef',
      },
    ],
    addon: null,
  },
  profilePasswordPage: {
    formTitle: null,
    formName: 'editPassword',
    formButton: {
      text: 'Сохранить',
    },
    inputs: [
      {
        type: 'password',
        labelText: 'Старый пароль',
        name: 'oldPassword',
        required: true,
        ref: 'oldPassword_inputRef',
        errorRef: 'oldPassword_errorRef',
        id: uuidv4(7),
      },
      {
        type: 'password',
        labelText: 'Новый пароль',
        name: 'newPassword',
        required: true,
        error: '',
        ref: 'newPassword_inputRef',
        errorRef: 'newPassword_errorRef',
        id: uuidv4(7),
      },
    ],
    addon: null,
  },
};
